version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
  # docker:
  #   image: docker:dind
  #   privileged: true
  #   environment:
  #     DOCKER_TLS_CERTDIR: /certs
  #   volumes:
  #     - jenkins-docker-certs:/certs/client
  #     - jenkins-data:/var/jenkins_home
  #   networks:
  #     - jenkins
  #   ports:
  #     - 2376:2376
volumes:
  jenkins-data:
  jenkins-docker-certs:

networks:
  jenkins:
