apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: consul-cert  #name of this object
  namespace: consul #same namespace as 
spec:
  dnsNames:
    - consul.ronforddigital.dev
  secretName: consul-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer